### ISSUE TITLE
Failed to generate sitemap. Error: TypeError: Cannot destructure property `Tags` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/plugin-sitemap-generator#12]
I'm seeing the following error(s) in MongoDB with job `{ type: "sitemaps/generate" }` using `sitemap-generator 1.2.1`:

<img width="950" alt="Screen Shot 2020-09-04 at 23 55 29" src="https://user-images.githubusercontent.com/65664227/92260407-6d426280-ef0a-11ea-9872-d9ba1f66f83c.png">

Full error text included in issue title. Appears to be related to the following line of code:

https://github.com/reactioncommerce/api-plugin-sitemap-generator/blob/8f06ee8ec2d96dd0057faf15fd47dc4a2879efb6/src/util/generate-sitemaps.js#L68

To replicate issue run the following mutation on the primary shop and wait for the job to abend:

```graphql
mutation GenerateSitemaps {
  generateSitemaps(
    input: {
      shopId: "cmVhY3Rpb24vc2hvcDphU1lHMnhtZkNGRkZrampCZQ=="
    }
  ), {
    wasJobScheduled
  }
}
```

Then inspect `failures` of most recent `"sitemaps/generate"` job via MongoDB or [Job Control Interface/API](https://github.com/reactioncommerce/reaction-feature-requests/issues/132) if available.

**Comment by balibebas** [comment]
Error occurs on the following line, not the one previously suggested:

https://github.com/reactioncommerce/api-plugin-sitemap-generator/blob/8f06ee8ec2d96dd0057faf15fd47dc4a2879efb6/src/util/generate-sitemaps.js#L199

Issue occurs due to attempt to destructure `Tags` from `undefined` because calling function does not pass `context` as we can see here:

https://github.com/reactioncommerce/api-plugin-sitemap-generator/blob/8f06ee8ec2d96dd0057faf15fd47dc4a2879efb6/src/util/generate-sitemaps.js#L102

**Comment by ghost** [comment]
Error occurs on the following line, not the one previously suggested:

https://github.com/reactioncommerce/api-plugin-sitemap-generator/blob/8f06ee8ec2d96dd0057faf15fd47dc4a2879efb6/src/util/generate-sitemaps.js#L199

Issue occurs because calling function passes `shopId` but not `context`:

https://github.com/reactioncommerce/api-plugin-sitemap-generator/blob/8f06ee8ec2d96dd0057faf15fd47dc4a2879efb6/src/util/generate-sitemaps.js#L102
